version: "3.8"

services:
  # ===============================
  # 1) FRONTEND
  # ===============================
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - banking_network

  # ===============================
  # 2) DATABASE
  # ===============================
  db_container_test:
    build: ./DB
    container_name: db_container_test
    restart: "no"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./DB/Scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - banking_network

  # ===============================
  # 3) FLASK API
  # ===============================
  flask-app:
    build: ./API
    container_name: api_container_test
    restart: "no"
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db_container_test
    command: ["/entrypoint.sh"]
    depends_on:
      - db_container_test
    networks:
      - banking_network

# ===============================
# NETWORKS (INTERNAL, AUTO-CREATED)
# ===============================
networks:
  banking_network:
    driver: bridge

# ===============================
# VOLUMES
# ===============================
volumes:
  mysql_data:
